# Basic Java 21 configuration
image: gitpod/workspace-java-17

# VS Code Java extensions
vscode:
  extensions:
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-test
    - vscjava.vscode-maven
